version: "3.7" # optional since v1.27.0
services:
  web:
    image: xacnio/ekira-backend:latest
    ports:
      - "4343:4343"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./.env.dev:/app/.env.dev
      - ./logs:/app/logs
      - ./public:/app/public
    environment:
      TZ: "Europe/Istanbul"
      RUN_TYPE: "dev"
  postgres:
    hostname: postgres
    image: postgres
    ports:
      - '4344:5432'
    environment:
      - TZ=Europe/Istanbul
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./platform/database/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "4345:6379"
    restart: unless-stopped
    environment:
      - TZ=Europe/Istanbul
      - REDIS_PASSWORD=${REDIS_PASS}
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "7555:80"
    restart: unless-stopped
    environment:
      TZ: "Europe/Istanbul"
